#tag: 00_00_03 date:21/03/2020
#Modification du nom du container sysart_bookstack en sysart_web et changement de répertoire pour les deux volumes
version: '2'

services:

  sysart_db:
    image: mysql:5.7.21
    container_name: sysart_db
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - "/apps/sysartbookstackmysql/volumes/mysql:/var/lib/mysql"

  sysart_web:
    image: solidnerd/bookstack:0.27.5
    container_name: sysart_web
    restart: always
    depends_on:
    - sysart_db
    environment:
    - DB_HOST=${MYSQL_DATABASE}
    - DB_DATABASE=${MYSQL_DATABASE}
    - DB_USERNAME=${MYSQL_USER}
    - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - "/apps/sysartbookstackmysql/volumes/bookstack/uploads:/var/www/bookstack/public/uploads/"
    - "/apps/sysartbookstackmysql/volumes/bookstack/storage-uploads:/var/www/bookstack/storage/uploads"
    ports:
    - "6802:80"
